apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  ports:
    - port: {{ .Values.webserver.servicePort}}
      targetPort: {{ .Values.webserver.containerPort}}
  selector:
    app: webserver
